import type { Metadata } from 'next';
import './globals.css';
import { UserAuthContextProvider } from '@/context/UserAuthContext';
import { OKXAuthContextProvider } from '@/context/OKXAuthContext';

export const metadata: Metadata = {
  title: 'eth-dapp-starter',
  description: 'Generated by eth-dapp-starter',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <OKXAuthContextProvider>
        <UserAuthContextProvider>
          <body className={`antialiased`}>{children}</body>
        </UserAuthContextProvider>
      </OKXAuthContextProvider>
    </html>
  );
}
