import type { Metadata } from 'next';
import './globals.css';
import { UserAuthContextProvider } from '@/context/UserAuthContext';
import { OKXAuthContextProvider } from '@/context/OKXAuthContext';

export const metadata: Metadata = {
  title: 'eth-dapp-starter',
  description: 'Generated by eth-dapp-starter',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Surpress hydration warning
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className="min-h-screen">
        <OKXAuthContextProvider>
          <UserAuthContextProvider>
            <main className="antialiased">{children}</main>
          </UserAuthContextProvider>
        </OKXAuthContextProvider>
      </body>
    </html>
  );
}
