import type { Metadata } from 'next';
import './globals.css';
import { AuthContextProvider } from '@/context/AuthContext';

export const metadata: Metadata = {
  title: 'eth-dapp-starter',
  description: 'Generated by eth-dapp-starter',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <body className={`antialiased`}>{children}</body>
      </AuthContextProvider>
    </html>
  );
}
